#include "../main.h"

int main(int argc, char **argv)
{
	int len, len2;
	long int l = INT_MIN;
	long int lm = UINT_MAX;
	long res = INT_MAX;
	int TASK_NUM = 0;

	(void)l;
	(void)lm;
	(void)res;
	(void)argc;
	
	if (argc > 2)
	{
		printf("program only accepts 1 parameter: number of the task to perform");
	}
	if (argc == 2)
		TASK_NUM = atoi(argv[1]);

	printf("task asked for: %d\n\n", TASK_NUM);

	switch (TASK_NUM)
	{
	case 0:
		printf("TEST CASES FOR TASK %d\n======================\n====================\n", TASK_NUM);
		printf("PRUEBA 0 ============================\n");
		len2 = printf("Let's print a simple sentence.\n");
		printf("%d\n", len2);
		len = _printf("Let's print a simple sentence.\n");
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 1 ============================\n");
		len2 = printf("%c", 'S');
		printf("%d\n", len2);
		len = _printf("%c", 'S');
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 2 ============================\n");
		len2 = printf("A char inside a sentence: %c. Did it work?\n", 'F');
		printf("%d\n", len2);
		len = _printf("A char inside a sentence: %c. Did it work?\n", 'F');
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 3 ============================\n");
		len2 = printf("Let'see if the cast is correctly done: %c. Did it work?\n", 48);
		printf("%d\n", len2);
		len = _printf("Let'see if the cast is correctly done: %c. Did it work?\n", 48);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 4 ============================\n");
		len2 = printf("%s", "This sentence is retrieved from va_args!\n");
		printf("%d\n", len2);
		len = _printf("%s", "This sentence is retrieved from va_args!\n");
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 5 ============================\n");
		len2 = printf("Complete the sentence: You %s nothing, Jon Snow.\n", "know");
		printf("%d\n", len2);
		len = _printf("Complete the sentence: You %s nothing, Jon Snow.\n", "know");
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 6 ============================\n");
		len2 = printf("Complete the sentence: You %s nothing, Jon Snow.\n", (char *)0);
		printf("%d\n", len2);
		len = _printf("Complete the sentence: You %s nothing, Jon Snow.\n", (char *)0);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 7 ============================\n");
		len2 = printf("%c%cth %s%s a%cg%s: Y%sou %s no%ching%s Snow.%c", 'W', 'i', "some ", "more", 'r', "s", "", "know", 't', ", Jon", '\n');
		printf("%d\n", len2);
		len = _printf("%c%cth %s%s a%cg%s: Y%sou %s no%ching%s Snow.%c", 'W', 'i', "some ", "more", 'r', "s", "", "know", 't', ", Jon", '\n');
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 8 ============================\n");
		len2 = printf("%%");
		printf("%d\n", len2);
		len = _printf("%%");
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 9 ============================\n");
		len2 = printf("Should print a single percent sign: %%\n");
		printf("%d\n", len2);
		len = _printf("Should print a single percent sign: %%\n");
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 10 ============================\n");
		len2 = printf("%s%c%c%c%s%%%s%c", "Loading ", '.', '.', '.', " 99", " Please wait", '\n');
		printf("%d\n", len2);
		len = _printf("%s%c%c%c%s%%%s%c", "Loading ", '.', '.', '.', " 99", " Please wait", '\n');
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 11 ============================\n");
		len2 = printf("css%ccs%scscscs", 'T', "Test");
		printf("%d\n", len2);
		len = _printf("css%ccs%scscscs", 'T', "Test");
		printf("%d\n", len);
		fflush(stdout);
		/* printf("PRUEBA 12 ============================\n");
	  len2 = printf(str); printf("%d\n", len2);
                        len = _printf(str); printf("%d\n", len);
                        fflush(stdout); 
			printf("PRUEBA 13 ============================\n");
			len2 = printf("man gcc:\n%s", str); printf("%d\n", len2);
			len = _printf("man gcc:\n%s", str); printf("%d\n", len);
			fflush(stdout); */
		printf("PRUEBA 14 ============================\n");
		len2 = printf(NULL);
		printf("%d\n", len2);
		len = _printf(NULL);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 15 ============================\n");
		len2 = printf("%c", '\0');
		printf("%d\n", len2);
		len = _printf("%c", '\0');
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 16 ============================\n");
		len2 = printf("%");
		printf("%d\n", len2);
		len = _printf("%");
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 17 ============================\n");
		len2 = printf("%!\n");
		printf("%d\n", len2);
		len = _printf("%!\n");
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 18 ============================\n");
		len2 = printf("%K\n");
		printf("%d\n", len2);
		len = _printf("%K\n");
		printf("%d\n", len);
		fflush(stdout);
		break;

	case 1:
		printf("TEST CASES FOR TASK %d\n======================\n====================\n", TASK_NUM);
		printf("PRUEBA 0 ============================\n");
		len2 = printf("%d", 1024);
		printf("%d\n", len2);
		len = _printf("%d", 1024);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 1 ============================\n");
		len2 = printf("%d", -1024);
		printf("%d\n", len2);
		len = _printf("%d", -1024);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 2 ============================\n");
		len2 = printf("%d", 0);
		printf("%d\n", len2);
		len = _printf("%d", 0);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 3 ============================\n");
		len2 = printf("%d", INT_MAX);
		printf("%d\n", len2);
		len = _printf("%d", INT_MAX);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 4 ============================\n");
		len2 = printf("%d", INT_MIN);
		printf("%d\n", len2);
		len = _printf("%d", INT_MIN);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 5 ============================\n");
		l -= 1024;
		len2 = printf("%d", l);
		printf("%d\n", len2);
		len = _printf("%d", l);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 6 ============================\n");
		len2 = printf("There is %d bytes in %d KB\n", 1024, 1);
		printf("%d\n", len2);
		len = _printf("There is %d bytes in %d KB\n", 1024, 1);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 7 ============================\n");
		len2 = printf("%d - %d = %d\n", 1024, 2048, -1024);
		printf("%d\n", len2);
		len = _printf("%d - %d = %d\n", 1024, 2048, -1024);
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 8 ============================\n");
		len2 = printf("%d + %d = %d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
		printf("%d\n", len2);
		len = _printf("%d + %d = %d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
		printf("%d\n", len);
		fflush(stdout);
		printf("PRUEBA 9 ============================\n");
		len2 = printf("%i", 1024);
		printf("\n%d\n", len2);
		len = _printf("%i", 1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 10 ============================\n");
		len2 = printf("%i", -1024);
		printf("\n%d\n", len2);
		len = _printf("%i", -1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 11 ============================\n");
		len2 = printf("%i", 0);
		printf("\n%d\n", len2);
		len = _printf("%i", 0);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 12 ============================\n");
		len2 = printf("%i", INT_MAX);
		printf("\n%d\n", len2);
		len = _printf("%i", INT_MAX);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 13 ============================\n");
		len2 = printf("%i", INT_MIN);
		printf("\n%d\n", len2);
		len = _printf("%i", INT_MIN);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 14 ============================\n");
		l += 1024;
		len2 = printf("%i", l);
		printf("\n%d\n", len2);
		len = _printf("%i", l);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 15 ============================\n");
		l -= 1024;
		len2 = printf("%i", l);
		printf("\n%d\n", len2);
		len = _printf("%i", l);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 16 ============================\n");
		len2 = printf("There is %i bytes in %i KB\n", 1024, 1);
		printf("\n%d\n", len2);
		len = _printf("There is %i bytes in %i KB\n", 1024, 1);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 17 ============================\n");
		len2 = printf("%i - %i = %i\n", 1024, 2048, -1024);
		printf("\n%d\n", len2);
		len = _printf("%i - %i = %i\n", 1024, 2048, -1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 18 ============================\n");
		len2 = printf("%i + %i = %i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
		printf("\n%d\n", len2);
		len = _printf("%i + %i = %i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 19 ============================\n");
		len2 = printf("%d == %i\n", 1024, 1024);
		printf("\n%d\n", len2);
		len = _printf("%d == %i\n", 1024, 1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 19 ============================\n");
		len2 = printf("iddi%diddiiddi\n", 1024);
		printf("\n%d\n", len2);
		len = _printf("iddi%diddiiddi\n", 1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 20 ============================\n");
		len2 = printf("%d", 10000);
		printf("\n%d\n", len2);
		len = _printf("%d", 10000);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 21 ============================\n");
		len2 = printf("%i", 10000);
		printf("\n%d\n", len2);
		len = _printf("%i", 10000);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("FINAL ============================\n");
		break;

	case 2:
		printf("TEST CASES FOR TASK %d\n======================\n======================\n\n", TASK_NUM);
		printf("PRUEBA 0 ============================\n");
		len2 = printf("10000000000");
		printf("\n%d\n", len2);
		len = _printf("%b", 1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 1 ============================\n");
		len2 = printf("11111111111111111111110000000000");
		printf("\n%d\n", len2);
		len = _printf("%b", -1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 2 ============================\n");
		len2 = printf("0");
		printf("\n%d\n", len2);
		len = _printf("%b", 0);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 3 ============================\n");
		len2 = printf("11111111111111111111111111111111");
		printf("\n%d\n", len2);
		len = _printf("%b", UINT_MAX);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 4 ============================\n");
		l = UINT_MAX;
		l += 1024;
		len2 = printf("1111111111");
		printf("\n%d\n", len2);
		len = _printf("%b", l);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 5 ============================\n");
		len2 = printf("There is 10000000000 bytes in 1 KB\n");
		printf("\n%d\n", len2);
		len = _printf("There is %b bytes in %b KB\n", 1024, 1);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 6 ============================\n");
		len2 = printf("100000000000 - 10000000000 = 10000000000\n");
		printf("\n%d\n", len2);
		len = _printf("%b - %b = %b\n", 2048, 1024, 1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 7 ============================\n");
		res *= 2;
		len2 = printf("1111111111111111111111111111111 + 1111111111111111111111111111111 = 11111111111111111111111111111110\n");
		printf("\n%d\n", len2);
		len = _printf("%b + %b = %b\n", INT_MAX, INT_MAX, res);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("FINAL ============================\n");
		break;

	case 3:
		printf("TEST CASES FOR TASK %d\n======================\n======================\n\n", TASK_NUM);
		printf("PRUEBA 0 ============================\n");
		len2 = printf("%u", 1024);
		printf("\n%d\n", len2);
		len = _printf("%u", 1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 1 ============================\n");
		len2 = printf("%u", -1024);
		printf("\n%d\n", len2);
		len = _printf("%u", -1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 2 ============================\n");
		len2 = printf("%u", 0);
		printf("\n%d\n", len2);
		len = _printf("%u", 0);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 3 ============================\n");
		len2 = printf("%u", UINT_MAX);
		printf("\n%d\n", len2);
		len = _printf("%u", UINT_MAX);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 4 ============================\n");
		l += 1024;
		len2 = printf("%u", l);
		printf("\n%d\n", len2);
		len = _printf("%u", l);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 5 ============================\n");
		len2 = printf("There is %u bytes in %u KB\n", 1024, 1);
		printf("\n%d\n", len2);
		len = _printf("There is %u bytes in %u KB\n", 1024, 1);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 6 ============================\n");
		len2 = printf("%u - %u = %u\n", 2048, 1024, 1024);
		printf("\n%d\n", len2);
		len = _printf("%u - %u = %u\n", 2048, 1024, 1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 7 ============================\n");
		res *= 2;
		len2 = printf("%u + %u = %u\n", INT_MAX, INT_MAX, res);
		printf("\n%d\n", len2);
		len = _printf("%u + %u = %u\n", INT_MAX, INT_MAX, res);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 8 ============================\n");
		len2 = printf("%o", 1024);
		printf("\n%d\n", len2);
		len = _printf("%o", 1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 9 ============================\n");
		len2 = printf("%o", -1024);
		printf("\n%d\n", len2);
		len = _printf("%o", -1024);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 10 ============================\n");
		len2 = printf("%o", 0);
		printf("\n%d\n", len2);
		len = _printf("%o", 0);
		printf("\n%d\n", len);
		fflush(stdout);
		printf("FINAL ============================\n");
		break;
	case 8:
		printf("TEST CASES FOR TASK %d\n======================\n======================\n\n", TASK_NUM);
		printf("PRUEBA 0 ============================\n");
		len2 = printf("%+d", 1024); printf("\n%d\n", len2);
		len = _printf("%+d", 1024); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 1 ============================\n");
		len2 = printf("%+d", -1024); printf("\n%d\n", len2);
		len = _printf("%+d", -1024); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 2 ============================\n");
		len2 = printf("%+d", 0); printf("\n%d\n", len2);
		len = _printf("%+d", 0); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 3 ============================\n");
		len2 = printf("%+d", INT_MAX); printf("\n%d\n", len2);
		len = _printf("%+d", INT_MAX); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 4 ============================\n");
		len2 = printf("%+d", INT_MAX); printf("\n%d\n", len2);
		len = _printf("%+d", INT_MAX); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 5 ============================\n");
		len2 = printf("% d", 1024); printf("\n%d\n", len2);
		len = _printf("% d", 1024); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 6 ============================\n");
		len2 = printf("% d", -1024); printf("\n%d\n", len2);
		len = _printf("% d", -1024); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 7 ============================\n");
		len2 = printf("% i", 1024); printf("\n%d\n", len2);
		len = _printf("% i", 1024); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 8 ============================\n");
		len2 = printf("% +d + %+ d = % +i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len2);
		len = _printf("% +d + %+ d = % +i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len);
		printf("PRUEBA 9 ============================\n");
		len2 = printf("%#o", 1024); printf("\n%d\n", len2);
		len = _printf("%#o", 1024); printf("\n%d\n", len);
		fflush(stdout);			
		printf("PRUEBA 10 ============================\n");
		len2 = printf("%#o", 0); printf("\n%d\n", len2);
		len = _printf("%#o", 0); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 11 ============================\n");
		len2 = printf("%#o", UINT_MAX); printf("\n%d\n", len2);
		len = _printf("%#o", UINT_MAX); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 12 ============================\n");
		len2 = printf("% "); printf("\n%d\n", len2);
		len = _printf("% "); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 13 ============================\n");
		len2 = printf("% % % % "); printf("\n%d\n", len2);
		len = _printf("% % % % "); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 14 ============================\n");		
		len2 = printf("%#x", 1024); printf("\n%d\n", len2);
		len = _printf("%#x", 1024); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 15 ============================\n");		
		len2 = printf("%#X", 1024); printf("\n%d\n", len2);
		len = _printf("%#X", 1024); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 16 ============================\n");		
		len2 = printf("%#X", 0); printf("\n%d\n", len2);
		len = _printf("%#X", 0); printf("\n%d\n", len);
		fflush(stdout);
		printf("FINAL ============================\n");
		break;
	
	case 9:
		printf("TEST CASES FOR TASK %d\n======================\n======================\n\n", TASK_NUM);	
		printf("PRUEBA 0  ============================\n");
		len2 = printf("%#o", 1024); printf("\n%d\n", len2);
		len = _printf("%#o", 1024); printf("\n%d\n", len);
		fflush(stdout);	
		printf("PRUEBA 1  ============================\n");
		len2 = printf("%#o", 0); printf("\n%d\n", len2);
		len = _printf("%#o", 0); printf("\n%d\n", len);
		fflush(stdout);	
		printf("PRUEBA 38  ============================\n");
		len2 = printf("% i - % i = % i\n", 1024, 2048, -1024); printf("\n%d\n", len2);
		len = _printf("% i - % i = % i\n", 1024, 2048, -1024); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 39  ============================\n");
		len2 = printf("% i + % i = % i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len2);
		len = _printf("% i + % i = % i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 40  ============================\n");
		len2 = printf("% +i + %+ i = % +d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len2);
		len = _printf("% +i + %+ i = % +d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len);
		fflush(stdout);
		break;

	case 10:
		printf("Example: \n\n");
		printf("Result from standard library's printf: \n\n");	
		len2 = printf("\t--> Hello, %s. project took us %+d days, which in hexa is %#x\n", "World", 5, 5); printf("\t--> Lenth of string: %d\n\n", len2);
		printf("--------------------------------------------------------------------------\n");
		printf("\nResult from our _printf: \n\n");	
		len = _printf("\t--> Hello, %s. project took us %+d days, which in hexa is %#x\n", "World", 5, 5); printf("\t--> Length of string: %d\n\n\n", len);
		break;

	case 11:
		printf("TEST CASES FOR TASK %d\n======================\n======================\n\n", TASK_NUM);	
		printf("PRUEBA 41  ============================\n");
		len2 = printf("% +i + %+ i = % +d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len2);
		len = _printf("% +i + %+ i = % +d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 42  ============================\n");
		len2 = printf("% +d + %+ d = % +i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len2);
		len = _printf("% +d + %+ d = % +i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX)); printf("\n%d\n", len);
		fflush(stdout);
		break;

	case 14:
		printf("TEST CASES FOR TASK %d\n======================\n======================\n\n", TASK_NUM);	
		printf("PRUEBA 0  ============================\n");
		len2 = printf("!sgra_av morf deveirter si ecnetnes sihT\n"); printf("\n%d\n", len2);
		len = _printf("%r", "\nThis sentence is retrieved from va_args!"); printf("\n%d\n", len);
		fflush(stdout);
		break;
	case 15:
		printf("TEST CASES FOR TASK %d\n======================\n======================\n\n", TASK_NUM);	
		printf("PRUEBA 0  ============================\n");
		len2 = printf("Complete the sentence: You  nothing, Jon Snow.\n"); printf("\n%d\n", len2);
		len = _printf("Complete the sentence: You %R nothing, Jon Snow.\n", ""); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 1  ============================\n");
		len2 = printf("Complete the sentence: You know nothing, Jon Snow.\n"); printf("\n%d\n", len2);
		len = _printf("Complete the sentence: You %R nothing, Jon Snow.\n", "xabj"); printf("\n%d\n", len);
		fflush(stdout);
		printf("PRUEBA 2  ============================\n");
		len2 = printf("This sentence is retrieved from va_args!\n"); printf("\n%d\n", len2);
		len = _printf("%R", "Guvf fragrapr vf ergevrirq sebz in_netf!\n"); printf("\n%d\n", len);
		fflush(stdout);
		break;
	}
	


	return (0);
}
